"""Copy-Space Guard: deterministic data-movement audit and CI gate."""

__version__ = "0.2.6"

from .core import (  # noqa: F401
    BOUNDS_REASON_AUTO_EXHAUSTIVE,
    BOUNDS_REASON_AUTO_PARTIAL,
    BOUNDS_REASON_FRACTIONAL_HEURISTIC_PARTIAL,
    BOUNDS_REASON_FRACTIONAL_ODD_SUBSET,
    BOUNDS_REASON_READ1_WRITE1_COMPLETE,
    BoundsReason,
)

__all__ = [
    "__version__",
    "BOUNDS_REASON_AUTO_EXHAUSTIVE",
    "BOUNDS_REASON_AUTO_PARTIAL",
    "BOUNDS_REASON_FRACTIONAL_HEURISTIC_PARTIAL",
    "BOUNDS_REASON_FRACTIONAL_ODD_SUBSET",
    "BOUNDS_REASON_READ1_WRITE1_COMPLETE",
    "BoundsReason",
]
